services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: psql-password
      POSTGRES_USER: psql
      POSTGRES_DB: devdb
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432