server:
  port: 81
  address: 0.0.0.0
  servlet:
    context-path: /api

spring:
  #datasource:
  #  url: jdbc:postgresql://host.docker.internal:5432/devdb                #Makes the database a file based/consistent database
  #  username: psql
  #  password: psql-password
  #  driverClassName: org.postgresql.Driver

  #jpa:
  #  database-platform: org.hibernate.dialect.PostgreSQLDialect
  #  generate-ddl: true
  #  hibernate:
  #    ddl-auto: create            # used to be create